#!/bin/sh
set -eu

preview="$(printf '%s' "${MANAGEMENT_UI_PREVIEW:-false}" | tr '[:upper:]' '[:lower:]')"

export MANAGEMENT_UI_PREVIEW="$preview"
export MANAGEMENT_UI_TELEMETRY_ENABLED="${MANAGEMENT_UI_TELEMETRY_ENABLED:-true}"
export MANAGEMENT_UI_TELEMETRY_ENDPOINT="${MANAGEMENT_UI_TELEMETRY_ENDPOINT:-/api/telemetry}"
export MANAGEMENT_UI_TELEMETRY_SAMPLE_RATE="${MANAGEMENT_UI_TELEMETRY_SAMPLE_RATE:-1}"
export MANAGEMENT_UI_EVENTS_MODE="${MANAGEMENT_UI_EVENTS_MODE:-hybrid}"
export MANAGEMENT_UI_EVENTS_URL="${MANAGEMENT_UI_EVENTS_URL:-/api/realtime}"

envsubst '${MANAGEMENT_UI_PREVIEW} ${MANAGEMENT_UI_TELEMETRY_ENABLED} ${MANAGEMENT_UI_TELEMETRY_ENDPOINT} ${MANAGEMENT_UI_TELEMETRY_SAMPLE_RATE} ${MANAGEMENT_UI_EVENTS_MODE} ${MANAGEMENT_UI_EVENTS_URL}' \
    < /usr/share/nginx/html/runtime-config.template.js \
    > /usr/share/nginx/html/runtime-config.js
