x-build: &build
  context: .
  dockerfile: Dockerfile

x-runtime: &runtime
  restart: unless-stopped

x-management-client: &management-client
  MANAGEMENT_SERVICE_TOKEN: ${MANAGEMENT_SERVICE_TOKEN}

x-private-service: &private-service
  <<: *runtime

x-file-service: &file-service
  <<: *private-service
  volumes:
    - files:/files

services:
  management:
    <<: *runtime
    build:
      <<: *build
      target: management
    environment:
      MANAGEMENT_ENCRYPTION_KEY: ${MANAGEMENT_ENCRYPTION_KEY}
      MANAGEMENT_SERVICE_TOKEN: ${MANAGEMENT_SERVICE_TOKEN}
      MANAGEMENT_ADMIN_PASSWORD: ${MANAGEMENT_ADMIN_PASSWORD}
      MANAGEMENT_SESSION_SECRET: ${MANAGEMENT_SESSION_SECRET}
    volumes:
      - management:/management
      - files:/files

  auth:
    <<: *runtime
    build:
      <<: *build
      target: auth
    environment:
      GITHUB_OAUTH_CLIENT_ID: ${GITHUB_OAUTH_CLIENT_ID}
      GITHUB_OAUTH_CLIENT_SECRET: ${GITHUB_OAUTH_CLIENT_SECRET}
      GITHUB_OAUTH_JWT_SIGNING_KEY: ${GITHUB_OAUTH_JWT_SIGNING_KEY}
      GITHUB_OAUTH_ALLOWED_USERS: ${GITHUB_OAUTH_ALLOWED_USERS}
    volumes:
      - auth:/auth

  gateway:
    <<: *runtime
    build:
      <<: *build
      target: gateway
    environment:
      GITHUB_OAUTH_JWT_SIGNING_KEY: ${GITHUB_OAUTH_JWT_SIGNING_KEY}
      GITHUB_OAUTH_ALLOWED_USERS: ${GITHUB_OAUTH_ALLOWED_USERS}

  github:
    <<: *private-service
    depends_on:
      management:
        condition: service_healthy
        required: true
    build:
      <<: *build
      target: github
    environment:
      <<: *management-client

  gitlab:
    <<: *private-service
    depends_on:
      management:
        condition: service_healthy
        required: true
    build:
      <<: *build
      target: gitlab
    environment:
      <<: *management-client

  files:
    <<: *file-service
    build:
      <<: *build
      target: files
    environment:
      <<: *management-client

  curl:
    <<: *file-service
    build:
      <<: *build
      target: curl
    environment:
      <<: *management-client

  analysis:
    <<: *private-service
    depends_on:
      ghidra:
        condition: service_healthy
        required: true
    build:
      <<: *build
      target: analysis
    environment:
      <<: *management-client

  ghidra:
    <<: *private-service
    build:
      <<: *build
      target: ghidra
    environment:
      <<: *management-client
    networks:
      - default
      - coolify

volumes:
  management:
  files:
  auth:

networks:
  coolify:
    external: true
    name: coolify
