import { reactive, readonly } from "vue"
import { runtimeConfig } from "@/shared/config/runtime"
export type TelemetryLevel="debug"|"info"|"warn"|"error"
export interface FrontendTelemetryEvent { id:string; name:string; level:TelemetryLevel; occurredAt:string; durationMs?:number; route:string; attributes:Record<string,string|number|boolean|null> }
const buffer=reactive<FrontendTelemetryEvent[]>([])
const MAX_BUFFER=500
function safeAttributes(input:Record<string,unknown>={}):Record<string,string|number|boolean|null>{ const out:Record<string,string|number|boolean|null>={}; for(const [key,value] of Object.entries(input)){ const k=key.toLowerCase(); if(k.includes("password")||k.includes("credential")||k.includes("token")||k.includes("cookie")||k.includes("authorization")||k.includes("secret")||k.includes("payload")||k.includes("body"))continue; if(value===null||typeof value==="string"||typeof value==="number"||typeof value==="boolean")out[key]=typeof value==="string"?value.slice(0,500):value } return out }
function event(name:string,attributes:Record<string,unknown>={},options:{level?:TelemetryLevel;durationMs?:number}={}):FrontendTelemetryEvent { const item={id:crypto.randomUUID(),name,level:options.level??"info",occurredAt:new Date().toISOString(),durationMs:options.durationMs,route:location.hash||location.pathname,attributes:safeAttributes(attributes)}; buffer.unshift(item); if(buffer.length>MAX_BUFFER)buffer.splice(MAX_BUFFER); if(runtimeConfig.telemetry.enabled && Math.random()<=runtimeConfig.telemetry.sampleRate){ void fetch(runtimeConfig.telemetry.endpoint,{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json"},body:JSON.stringify(item),keepalive:true}).catch(()=>{}) } return item }
function error(name:string,caught:unknown,attributes:Record<string,unknown>={}):FrontendTelemetryEvent { return event(name,{...attributes,error_type:caught instanceof Error?caught.name:"unknown",error_message:caught instanceof Error?caught.message:String(caught).slice(0,500)},{level:"error"}) }
export const frontendTelemetry={ events:readonly(buffer), event, error, api(path:string,method:string,status:number,durationMs:number){return event("api.request",{path,method,status},{level:status>=500?"error":status>=400?"warn":"info",durationMs})}, navigation(id:string){return event("navigation",{page:id})}, websocket(state:string,topic?:string){return event("realtime.websocket",{state,topic:topic??null})} }
