import { reactive, readonly } from "vue"
import { runtimeConfig } from "@/shared/config/runtime"
import { frontendTelemetry } from "@/shared/telemetry/client"
export type EventTopic="mcp.calls"|"dashboard.metrics"|"browser.activity"|"system.notifications"|"runtime.state"|string
export interface BusEvent<T=unknown>{topic:EventTopic;type:string;occurredAt:string;data:T}
type Handler=(event:BusEvent)=>void
const handlers=new Map<EventTopic,Set<Handler>>()
const state=reactive({status:"idle" as "idle"|"connecting"|"connected"|"reconnecting"|"mock",subscriptions:0,lastEventAt:""})
let socket:WebSocket|null=null,reconnectTimer=0,reconnectAttempt=0
const sse=new Map<string,EventSource>()
function dispatch(event:BusEvent){state.lastEventAt=event.occurredAt; for(const handler of handlers.get(event.topic)??[])handler(event)}
function wireSseCompat(topic:EventTopic){ if(topic!=="mcp.calls"||sse.has(topic))return; const source=new EventSource("/api/calls/stream"); source.onopen=()=>{state.status="connected";frontendTelemetry.websocket("connected",topic)}; source.onerror=()=>{state.status="reconnecting";frontendTelemetry.websocket("reconnecting",topic)}; source.onmessage=e=>dispatch({topic,type:"item",occurredAt:new Date().toISOString(),data:JSON.parse(e.data)}); sse.set(topic,source) }
function closeSse(topic:EventTopic){const source=sse.get(topic); if(source){source.close();sse.delete(topic)}}
function connectWebSocket(){ if(runtimeConfig.events.mode==="mock"||socket)return; state.status="connecting"; const scheme=location.protocol==="https:"?"wss:":"ws:"; const url=runtimeConfig.events.url.startsWith("/")?`${scheme}//${location.host}${runtimeConfig.events.url}`:runtimeConfig.events.url; socket=new WebSocket(url); socket.onopen=()=>{state.status="connected";reconnectAttempt=0;frontendTelemetry.websocket("connected");for(const topic of handlers.keys())socket?.send(JSON.stringify({type:"subscribe",topic}))}; socket.onmessage=e=>{try{dispatch(JSON.parse(e.data) as BusEvent)}catch(err){frontendTelemetry.error("realtime.decode",err)}}; socket.onclose=()=>{socket=null;if(!handlers.size){state.status="idle";return}state.status="reconnecting";frontendTelemetry.websocket("reconnecting");const delay=Math.min(30000,1000*2**Math.min(reconnectAttempt++,5));reconnectTimer=window.setTimeout(connectWebSocket,delay)}; socket.onerror=()=>frontendTelemetry.websocket("error") }
function subscribe(topic:EventTopic,handler:Handler):()=>void { let set=handlers.get(topic); if(!set){set=new Set();handlers.set(topic,set)} set.add(handler); state.subscriptions=[...handlers.values()].reduce((n,s)=>n+s.size,0); if(runtimeConfig.events.mode==="hybrid")wireSseCompat(topic); else if(runtimeConfig.events.mode==="websocket")connectWebSocket(); else state.status="mock"; return()=>{const current=handlers.get(topic);current?.delete(handler);if(!current?.size){handlers.delete(topic);closeSse(topic);if(socket?.readyState===WebSocket.OPEN)socket.send(JSON.stringify({type:"unsubscribe",topic}))}state.subscriptions=[...handlers.values()].reduce((n,s)=>n+s.size,0);if(!handlers.size){clearTimeout(reconnectTimer);socket?.close();socket=null;state.status=runtimeConfig.events.mode==="mock"?"mock":"idle"}} }
function publishMock(topic:EventTopic,type:string,data:unknown){dispatch({topic,type,occurredAt:new Date().toISOString(),data})}
export const eventBus={state:readonly(state),subscribe,publishMock}
