<script setup lang="ts">
import { computed, onMounted, ref } from "vue"
import { Modal, Switch, Tag } from "ant-design-vue"
import { Plus, RefreshCw } from "lucide-vue-next"
import { managementApi, type AnalysisProjectState, type AnalysisState } from "@/shared/api/management"
import { textValue } from "@/shared/lib/format"
import Button from "@/shared/ui/Button.vue"
import DataTable from "@/shared/ui/DataTable.vue"
import PageHeader from "@/shared/ui/PageHeader.vue"

const state = ref<AnalysisState | null>(null); const loading = ref(false); const error = ref(""); const createOpen = ref(false); const projectName = ref(""); const parentDir = ref(""); const detail = ref<AnalysisProjectState | null>(null); const detailId = ref(""); const coverage = ref<Record<string, unknown> | null>(null)
const projects = computed(() => Array.isArray(state.value?.overview.projects) ? state.value!.overview.projects as Array<Record<string, unknown>> : [])
const workers = computed(() => Array.isArray(state.value?.overview.workers) ? state.value!.overview.workers as Array<Record<string, unknown>> : [])
const projectColumns = [{ title: "Name", dataIndex: "name", key: "name" }, { title: "Group", dataIndex: "group", key: "group", width: 160 }, { title: "Session", dataIndex: "session", key: "session", width: 110 }, { title: "Worker", dataIndex: "worker_index", key: "worker_index", width: 90 }, { title: "Path", dataIndex: "path", key: "path" }, { title: "Actions", key: "actions", width: 250 }]
const workerColumns = [{ title: "Worker", dataIndex: "worker_index", key: "worker_index", width: 90 }, { title: "Enabled", dataIndex: "enabled", key: "enabled", width: 110 }, { title: "Running", dataIndex: "running", key: "running", width: 100 }, { title: "Queued", dataIndex: "queued", key: "queued", width: 90 }, { title: "Project", dataIndex: "project_id", key: "project_id" }]
async function load() { loading.value = true; error.value = ""; try { state.value = await managementApi.analysis() } catch (e) { error.value = e instanceof Error ? e.message : "Unable to load analysis" } finally { loading.value = false } }
async function createProject() { await managementApi.createAnalysisProject(projectName.value, parentDir.value); createOpen.value = false; projectName.value = ""; parentDir.value = ""; await load() }
async function openProject(id: string) { await managementApi.openAnalysisProject(id); await load(); await inspect(id) }
async function releaseProject(id: string) { await managementApi.releaseAnalysisProject(id); await load(); detail.value = null }
async function deleteProject(id: string) { if (!window.confirm(`Delete project ${id}?`)) return; await managementApi.deleteAnalysisProject(id); await load(); detail.value = null }
async function setWorker(index: number, enabled: boolean) { await managementApi.setAnalysisWorker(index, enabled); await load() }
async function inspect(id: string) { detailId.value = id; detail.value = await managementApi.analysisProject(id) }
async function loadCoverage(program: unknown, full: boolean) { if (!detailId.value || typeof program !== "string") return; coverage.value = await managementApi.analysisCoverage(detailId.value, program, full) }
onMounted(load)
</script>
<template>
  <div class="space-y-6">
    <PageHeader title="Analysis" description="Reverse projects, worker allocation and documentation coverage."><Button variant="outline" size="sm" @click="load"><RefreshCw class="mr-2 size-4" />Refresh</Button><Button size="sm" @click="createOpen = true"><Plus class="mr-2 size-4" />New project</Button></PageHeader>
    <p v-if="error" class="text-sm text-destructive">{{ error }}</p>
    <div class="space-y-3"><h2 class="text-sm font-semibold">Projects</h2><DataTable :columns="projectColumns" :data-source="projects" :loading="loading" row-key="project_id"><template #bodyCell="{ column, record }"><template v-if="column.key === 'session'"><Tag :color="record.session === 'active' ? 'blue' : 'default'">{{ record.session }}</Tag></template><template v-else-if="column.key === 'actions'"><div class="flex gap-1"><Button variant="ghost" size="sm" @click="inspect(record.project_id)">Inspect</Button><Button v-if="record.session === 'active'" variant="ghost" size="sm" @click="releaseProject(record.project_id)">Release</Button><Button v-else variant="ghost" size="sm" @click="openProject(record.project_id)">Open</Button><Button variant="ghost" size="sm" @click="deleteProject(record.project_id)">Delete</Button></div></template></template></DataTable></div>
    <div class="space-y-3"><h2 class="text-sm font-semibold">Workers</h2><DataTable :columns="workerColumns" :data-source="workers" row-key="worker_index"><template #bodyCell="{ column, record }"><template v-if="column.key === 'enabled'"><Switch :checked="record.enabled !== false" @change="setWorker(Number(record.worker_index), $event as boolean)" /></template><template v-else-if="column.key === 'running'"><Tag :color="record.running ? 'green' : 'default'">{{ record.running ? 'running' : 'idle' }}</Tag></template></template></DataTable></div>
    <Modal v-model:open="createOpen" title="Create analysis project" @ok="createProject"><div class="space-y-3 py-3"><label class="block space-y-1 text-sm"><span>Name</span><input v-model="projectName" class="field" /></label><label class="block space-y-1 text-sm"><span>Parent directory</span><input v-model="parentDir" class="field" placeholder="optional" /></label></div></Modal>
    <Modal :open="Boolean(detail)" title="Analysis project" :footer="null" width="940px" @cancel="detail = null; coverage = null"><div v-if="detail" class="space-y-5 text-sm"><div class="grid gap-3 sm:grid-cols-3"><div><span class="text-muted-foreground">Session</span><div>{{ textValue(detail.session.session) }}</div></div><div><span class="text-muted-foreground">Project</span><div class="font-mono text-xs">{{ detailId }}</div></div><div><span class="text-muted-foreground">Programs</span><div>{{ detail.programs.length }}</div></div></div><div v-if="detail.programs.length" class="space-y-2"><div class="text-xs font-medium uppercase text-muted-foreground">Coverage</div><div class="flex flex-wrap gap-2" v-for="program in detail.programs" :key="String((program as any).name || (program as any).program || program)"><span class="min-w-48 font-mono text-xs">{{ (program as any).name || (program as any).program || String(program) }}</span><Button variant="outline" size="sm" @click="loadCoverage((program as any).name || (program as any).program || program, false)">Quick</Button><Button variant="outline" size="sm" @click="loadCoverage((program as any).name || (program as any).program || program, true)">Full</Button></div></div><pre v-if="coverage" class="max-h-72 overflow-auto rounded-lg bg-muted p-3 text-xs whitespace-pre-wrap">{{ JSON.stringify(coverage, null, 2) }}</pre><div class="space-y-2"><div class="text-xs font-medium uppercase text-muted-foreground">Project files</div><pre class="max-h-64 overflow-auto rounded-lg bg-muted p-3 text-xs whitespace-pre-wrap">{{ JSON.stringify(detail.files, null, 2) }}</pre></div></div></Modal>
  </div>
</template>
