<script setup lang="ts">
import { computed, onMounted, reactive, ref } from "vue"
import { InputNumber, Modal, Switch, Tag } from "ant-design-vue"
import { Plus, RefreshCw, Save } from "lucide-vue-next"
import { useI18n } from "vue-i18n"
import { managementApi, type AnalysisProjectState, type AnalysisState, type SettingsState } from "@/shared/api/management"
import { textValue } from "@/shared/lib/format"
import { notifications } from "@/shared/notifications/bus"
import { settingsUpdatePayload } from "@/shared/settings/payload"
import Button from "@/shared/ui/Button.vue"
import DataTable from "@/shared/ui/DataTable.vue"
import PageHeader from "@/shared/ui/PageHeader.vue"

const {t}=useI18n()
const state=ref<AnalysisState|null>(null),settings=ref<SettingsState|null>(null),loading=ref(false),error=ref(""),createOpen=ref(false),projectName=ref(""),parentDir=ref(""),detail=ref<AnalysisProjectState|null>(null),detailId=ref(""),coverage=ref<Record<string,unknown>|null>(null),idleTimeout=ref(900),savingPolicy=ref(false)
const workerActions=reactive<Record<number,"idle"|"clearing"|"recovering">>({})
const projects=computed(()=>Array.isArray(state.value?.overview.projects)?state.value!.overview.projects as Array<Record<string,unknown>>:[]),workers=computed(()=>Array.isArray(state.value?.overview.workers)?state.value!.overview.workers as Array<Record<string,unknown>>:[])
const projectColumns=[{title:t('analysis.name'),dataIndex:'name',key:'name'},{title:t('analysis.group'),dataIndex:'group',key:'group',width:160},{title:t('analysis.session'),dataIndex:'session',key:'session',width:110},{title:t('analysis.worker'),dataIndex:'worker_index',key:'worker_index',width:90},{title:t('analysis.path'),dataIndex:'path',key:'path'},{title:t('common.actions'),key:'actions',width:270}]
const workerColumns=[{title:t('analysis.worker'),dataIndex:'worker_index',key:'worker_index',width:90},{title:t('common.enabled'),dataIndex:'enabled',key:'enabled',width:110},{title:t('terminal.running'),dataIndex:'running',key:'running',width:100},{title:t('analysis.queued'),dataIndex:'queued',key:'queued',width:90},{title:t('common.project'),dataIndex:'project_id',key:'project_id'},{title:t('common.actions'),key:'actions',width:180}]
async function load(){loading.value=true;error.value='';try{const [overview,current]=await Promise.all([managementApi.analysis(),managementApi.settings()]);state.value=overview;settings.value=current;idleTimeout.value=Number(current.analysis.idle_timeout_seconds??900)}catch(e){error.value=e instanceof Error?e.message:'Unable to load analysis'}finally{loading.value=false}}
async function savePolicy(){if(!settings.value)return;savingPolicy.value=true;try{settings.value=await managementApi.updateSettings(settingsUpdatePayload(settings.value,{reverse_idle_timeout_seconds:idleTimeout.value}));notifications.success(String(t('notifications.saved')))}finally{savingPolicy.value=false}}
async function createProject(){await managementApi.createAnalysisProject(projectName.value,parentDir.value);createOpen.value=false;projectName.value='';parentDir.value='';notifications.success(String(t('notifications.saved')));await load()}
async function openProject(id:string){await managementApi.openAnalysisProject(id);await load();await inspect(id)}
async function releaseProject(id:string){await managementApi.releaseAnalysisProject(id);await load();detail.value=null}
async function deleteProject(id:string){if(!window.confirm(`Delete project ${id}?`))return;await managementApi.deleteAnalysisProject(id);notifications.success(String(t('notifications.deleted')),id);await load();detail.value=null}
async function setWorker(index:number,enabled:boolean){await managementApi.setAnalysisWorker(index,enabled);await load()}
async function clearWorkerQueue(index:number){workerActions[index]="clearing";try{await managementApi.clearAnalysisWorkerQueue(index);await load();notifications.success(String(t("analysis.queueCleared")))}catch(e){notifications.error(String(t("notifications.apiError")),e instanceof Error?e.message:String(e))}finally{workerActions[index]="idle"}}
async function recoverWorker(index:number){workerActions[index]="recovering";try{await managementApi.recoverAnalysisWorker(index);await load();notifications.success(String(t("analysis.workerRecovered")))}catch(e){notifications.error(String(t("notifications.apiError")),e instanceof Error?e.message:String(e))}finally{workerActions[index]="idle"}}
async function inspect(id:string){detailId.value=id;detail.value=await managementApi.analysisProject(id)}
async function loadCoverage(program:unknown,full:boolean){if(!detailId.value||typeof program!=="string")return;coverage.value=await managementApi.analysisCoverage(detailId.value,program,full)}
onMounted(load)
</script>
<template><div class="space-y-6"><PageHeader :title="t('nav.analysis')" :description="t('analysis.description')"><Button variant="outline" size="sm" @click="load"><RefreshCw class="mr-2 size-4"/>{{t('common.refresh')}}</Button><Button size="sm" @click="createOpen=true"><Plus class="mr-2 size-4"/>{{t('analysis.newProject')}}</Button></PageHeader><p v-if="error" class="text-sm text-destructive">{{error}}</p>
<section class="settings-card"><div class="flex items-center justify-between"><div><h2>{{t('settings.analysis')}}</h2><p class="text-xs text-muted-foreground">{{t('analysis.policyHint')}}</p></div><Button size="sm" :disabled="savingPolicy" @click="savePolicy"><Save class="mr-2 size-4"/>{{t('common.save')}}</Button></div><label class="setting-row"><span><b>{{t('analysis.idleTimeout')}}</b><small>{{t('analysis.idleTimeoutHint')}}</small></span><InputNumber v-model:value="idleTimeout" :min="0" :max="86400"/></label></section>
<div class="space-y-3"><h2 class="text-sm font-semibold">{{t('analysis.projects')}}</h2><DataTable :columns="projectColumns" :data-source="projects" :loading="loading" row-key="project_id" :pagination="false" virtual :scroll-y="520"><template #bodyCell="{column,record,value}"><template v-if="column.key==='session'"><Tag :color="record.session==='active'?'blue':'default'">{{record.session}}</Tag></template><template v-else-if="column.key==='actions'"><div class="flex gap-1"><Button variant="ghost" size="sm" @click="inspect(record.project_id)">{{t('analysis.inspect')}}</Button><Button v-if="record.session==='active'" variant="ghost" size="sm" @click="releaseProject(record.project_id)">{{t('analysis.release')}}</Button><Button v-else variant="ghost" size="sm" @click="openProject(record.project_id)">{{t('analysis.open')}}</Button><Button variant="ghost" size="sm" @click="deleteProject(record.project_id)">{{t('common.delete')}}</Button></div></template><template v-else><span class="truncate">{{value ?? '—'}}</span></template></template></DataTable></div>
<div class="space-y-3"><div class="flex items-end justify-between"><div><h2 class="text-sm font-semibold">{{t('analysis.workers')}}</h2><p class="mt-1 text-xs text-muted-foreground">{{t('analysis.workerRecoveryReady')}}</p></div></div><DataTable :columns="workerColumns" :data-source="workers" row-key="worker_index" :pagination="false"><template #bodyCell="{column,record,value}"><template v-if="column.key==='enabled'"><Switch :checked="record.enabled!==false" @change="setWorker(Number(record.worker_index),$event as boolean)"/></template><template v-else-if="column.key==='running'"><Tag :color="record.running?'green':'default'">{{record.running?t('analysis.running'):t('analysis.idle')}}</Tag></template><template v-else-if="column.key==='actions'"><div class="flex gap-1"><Button variant="ghost" size="sm" :disabled="Boolean(workerActions[Number(record.worker_index)] && workerActions[Number(record.worker_index)]!=='idle')" @click="clearWorkerQueue(Number(record.worker_index))">{{workerActions[Number(record.worker_index)]==='clearing'?t('common.loading'):t('analysis.clearQueue')}}</Button><Button variant="ghost" size="sm" :disabled="Boolean(workerActions[Number(record.worker_index)] && workerActions[Number(record.worker_index)]!=='idle')" @click="recoverWorker(Number(record.worker_index))">{{workerActions[Number(record.worker_index)]==='recovering'?t('common.loading'):t('analysis.recover')}}</Button></div></template><template v-else><span class="truncate">{{value ?? '—'}}</span></template></template></DataTable></div>
<Modal v-model:open="createOpen" :title="t('analysis.createTitle')" @ok="createProject"><div class="space-y-3 py-3"><label class="block space-y-1 text-sm"><span>{{t('analysis.name')}}</span><input v-model="projectName" class="field"/></label><label class="block space-y-1 text-sm"><span>{{t('analysis.parentDir')}}</span><input v-model="parentDir" class="field" :placeholder="t('analysis.optional')"/></label></div></Modal>
<Modal :open="Boolean(detail)" :title="t('analysis.projectTitle')" :footer="null" width="940px" @cancel="detail=null;coverage=null"><div v-if="detail" class="space-y-5 text-sm"><div class="grid gap-3 sm:grid-cols-3"><div><span class="text-muted-foreground">{{t('analysis.session')}}</span><div>{{textValue(detail.session.session)}}</div></div><div><span class="text-muted-foreground">{{t('common.project')}}</span><div class="font-mono text-xs">{{detailId}}</div></div><div><span class="text-muted-foreground">{{t('analysis.programs')}}</span><div>{{detail.programs.length}}</div></div></div><div v-if="detail.programs.length" class="space-y-2"><div class="text-xs font-medium uppercase text-muted-foreground">{{t('analysis.coverage')}}</div><div v-for="program in detail.programs" :key="String((program as any).name||(program as any).program||program)" class="flex flex-wrap gap-2"><span class="min-w-48 font-mono text-xs">{{(program as any).name||(program as any).program||String(program)}}</span><Button variant="outline" size="sm" @click="loadCoverage((program as any).name||(program as any).program||program,false)">{{t('analysis.quick')}}</Button><Button variant="outline" size="sm" @click="loadCoverage((program as any).name||(program as any).program||program,true)">{{t('analysis.full')}}</Button></div></div><pre v-if="coverage" class="max-h-72 overflow-auto rounded-lg bg-muted p-3 text-xs whitespace-pre-wrap">{{JSON.stringify(coverage,null,2)}}</pre><div class="space-y-2"><div class="text-xs font-medium uppercase text-muted-foreground">{{t('analysis.projectFiles')}}</div><pre class="max-h-64 overflow-auto rounded-lg bg-muted p-3 text-xs whitespace-pre-wrap">{{JSON.stringify(detail.files,null,2)}}</pre></div></div></Modal></div></template>
